/* ============ Pontos AI: Real bilingual content (RU/EN) ============ */

const PONTOS_CONTENT = {
  ru: {
    nav: {
      work: 'Дорожная карта',
      services: 'Источники',
      about: 'Команда',
      contact: 'Поддержать',
      chat: 'Pontos AI',
    },
    hero: {
      coords: 'Εύξεινος Πόντος · VII в. до н.э. — наши дни',
      label: 'Проект сохранения языка',
      title1: 'Πόντος AI',
      title2: 'Language',
      title3Em: 'Engine',
      title3: '.',
      tagline: 'Цифровой мозг понтийского греческого языка. 36 000+ слов · 2 600 лет истории · 20 диалектных регионов.',
      taglineLabel: '« Ζήτω ο Πόντος » — Да здравствует Понт',
      cta: 'Поговорить с Pontos AI',
      ctaSecondary: 'Дорожная карта',
      scroll: 'Прокрутить · κύλιση',
    },
    marquee: ['Τραπεζοῦς', 'Sinope', 'Ἀμισός', 'Κερασοῦς', 'Κωνσταντινούπολις', 'Κριμαία', 'Красная Поляна'],
    stats: [
      { num: '36 000+', label: 'Слов в базе' },
      { num: '2 600', label: 'Лет истории' },
      { num: '20', label: 'Диалектных регионов' },
      { num: '4', label: 'Алфавита · алф.' },
    ],
    manifesto: {
      label: 'Архитектура проекта · 01',
      title: 'Понтийский греческий — ',
      titleEm: 'живой язык в цифре.',
      meta: [
        ['Создатель', 'Maximian Solomonidis'],
        ['Места', 'Красная Поляна · Трапезунд'],
        ['Платформа', 'Persei.io · Evera.world'],
        ['Языки', 'RU · EN · ΕΛ · TR'],
      ],
      paragraphs: [
        <>Понтийский — наследие 2 600 лет, от черноморских колоний античности до сёл Трапезунда, Синопа и диаспоры. Мы строим <em>цифровой мозг</em> языка: словари, грамматику, этимологию и голоса носителей в одной живой системе.</>,
        <>Проект объединяет академические словари, фольклорные архивы и AI, который отвечает <em>только</em> из проверенной базы — без выдумок. Если слова нет — система говорит об этом честно.</>,
      ],
    },
    pillars: {
      label: 'Возможности · 02',
      title: 'Четыре опоры,',
      titleEm: 'один язык.',
      items: [
        { greek: '📖', name: 'Словарь', desc: 'Поиск по 36 000+ словам. Карточка слова: греческий, кириллица, латиница, этимология, диалект, источник.' },
        { greek: '🔡', name: 'Алфавиты', desc: 'Система понимает греческое, кириллическое, латинское и турецкое написание одного слова.' },
        { greek: '🎯', name: 'Без выдумок', desc: 'AI отвечает только из базы. Если слова нет — говорит об этом честно. Никаких галлюцинаций.' },
        { greek: '🚧', name: 'Скоро', desc: 'Полный чат с историей, грамматикой, культурой и песнями — встраивается прямо в этот сайт.' },
      ],
    },
    services: {
      label: 'База знаний · 03',
      title: 'Литература ',
      titleEm: 'и источники.',
      items: [
        { num: '/01', title: <>Академические <em>словари</em></>, desc: 'Папаниколау, Андриотис, Опатос — классические лексикографические труды по понтийскому диалекту.' },
        { num: '/02', title: <>Фольклорные <em>архивы</em></>, desc: 'Песни, пословицы, сказки, обрядовые тексты — голос языка, как он звучит в быту.' },
        { num: '/03', title: <>Голоса <em>носителей</em></>, desc: 'Полевые записи и аудиоматериалы из сёл Понта, Кавказа, Греции и диаспоры.' },
        { num: '/04', title: <>Ожидаемые <em>издания</em></>, desc: 'Новые публикации, диссертации и архивные материалы, готовящиеся к включению в базу.' },
      ],
    },
    work: {
      label: 'Дорожная карта · 04',
      title: '20 этапов от ',
      titleEm: 'архива до диалога.',
      items: [
        { num: '01', title: <>Сбор <em>источников</em></>, desc: 'Сканирование академических словарей, оцифровка фольклорных архивов и полевых материалов.', tags: ['Готово', '36k слов'] },
        { num: '02', title: <>Кросс-<em>алфавитный индекс</em></>, desc: 'Греческое, кириллическое, латинское и турецкое написание одного слова — единая база.', tags: ['Готово', 'Search'] },
        { num: '03', title: <>Карточка <em>слова</em></>, desc: 'Перевод, этимология, диалект, источник и примеры использования в одном представлении.', tags: ['Готово', 'UI'] },
        { num: '04', title: <>Базовый <em>AI-диалог</em></>, desc: 'Dictionary Mode: AI отвечает только из проверенной базы, без галлюцинаций.', tags: ['Готово', 'AI'] },
        { num: '05', title: <>Этимологические <em>цепочки</em></>, desc: 'Связи между древнегреческим, средневековым и современным понтийским словоупотреблением.', tags: ['В работе', 'Linguistics'] },
        { num: '06', title: <>Диалектные <em>регионы</em></>, desc: 'Карта 20 диалектных зон — от Трапезунда и Синопа до Ромеики и Кавказа.', tags: ['В работе', 'Map'] },
        { num: '07', title: <>Грамматические <em>таблицы</em></>, desc: 'Спряжения, склонения, морфология понтийского с примерами для каждой формы.', tags: ['В работе', 'Grammar'] },
        { num: '08', title: <>Фразеология и <em>идиомы</em></>, desc: 'Устойчивые выражения, поговорки, формулы вежливости и обрядовые формы.', tags: ['В работе', 'Phrases'] },
        { num: '09', title: <>Голос и <em>аудио</em></>, desc: 'Озвучка карточек носителями, песни и фонетика для каждого диалекта.', tags: ['Q3 2026', 'Audio'] },
        { num: '10', title: <>Корпус <em>текстов</em></>, desc: 'Поисковый корпус: фольклор, публикации, переводы — с конкордансом и контекстами.', tags: ['Q3 2026', 'Corpus'] },
        { num: '11', title: <>Песни и <em>μοιρολόγια</em></>, desc: 'Цифровой архив понтийских песен с лирикой, переводом и аудио.', tags: ['Q3 2026', 'Music'] },
        { num: '12', title: <>Школьный <em>модуль</em></>, desc: 'Интерактивные уроки, упражнения и карточки для изучающих язык.', tags: ['Q4 2026', 'Education'] },
        { num: '13', title: <>Игровые <em>тренажёры</em></>, desc: 'Карточки на запоминание, фонетические игры, мини-квесты по культуре.', tags: ['Q4 2026', 'Gamified'] },
        { num: '14', title: <>API и <em>SDK</em></>, desc: 'Открытое API для исследователей, школ и культурных проектов.', tags: ['Q4 2026', 'Dev'] },
        { num: '15', title: <>Полный <em>AI-чат</em></>, desc: 'Grammar, культура, песни и свободный диалог — встраивается прямо в pontos.world.', tags: ['Q4 2026', 'Chat'] },
        { num: '16', title: <>Голосовой <em>ввод</em></>, desc: 'Распознавание речи на понтийском — поиск и диалог голосом.', tags: ['2027', 'Voice'] },
        { num: '17', title: <>Литературное <em>издательство</em></>, desc: 'Цифровая библиотека книг, периодики и архивных публикаций.', tags: ['2027', 'Library'] },
        { num: '18', title: <>Социальный <em>слой</em></>, desc: 'Профили носителей и исследователей, обсуждения и совместное редактирование.', tags: ['2027', 'Social'] },
        { num: '19', title: <>Мобильные <em>приложения</em></>, desc: 'iOS и Android: словарь, чат, тренажёры и аудио — оффлайн-доступ.', tags: ['2027', 'Mobile'] },
        { num: '20', title: <>Живой <em>диалог</em></>, desc: 'Полная цифровая экосистема: дом понтийского языка для каждого, кто его ищет.', tags: ['Vision', 'Future'] },
      ],
    },
    chat: {
      label: 'Pontos AI · Dictionary Mode',
      title: 'Поговорить ',
      titleEm: 'с Понтом.',
      desc: '36 000+ слов · Греческий · Кириллица · Латиница · Турецкий',
      placeholder: 'Введите слово на любом алфавите — русском, греческом, латинском или турецком',
      examples: ['νερόν', 'вода', 'aman', 'Τραπεζοῦς', 'кровь', 'αίμαν'],
      cta: 'Открыть Pontos AI',
    },
    team: {
      label: 'Команда · 05',
      title: 'Носители, учёные, ',
      titleEm: 'инженеры.',
      desc: 'Вы носитель языка, филолог или исследователь? Присоединяйтесь — каждый голос бесценен.',
      cta: 'Присоединиться к проекту',
    },
    support: {
      label: 'Поддержать · 06',
      title: 'Помочь ',
      titleEm: 'проекту.',
      desc: 'Раздел поддержки в разработке. Сейчас лучший способ помочь — поделиться проектом или связаться напрямую.',
      items: [
        { icon: '🗣️', title: 'Носитель языка', desc: 'Запишите слова, фразы, песни, пословицы — ваш голос бесценен.', cta: 'Написать' },
        { icon: '🔬', title: 'Исследователь', desc: 'Помогите с проверкой данных, этимологией, грамматикой.', cta: 'Написать' },
        { icon: '💛', title: 'Финансово', desc: 'Платёжный модуль скоро. Проект строится на энтузиазме и любви к языку.', cta: 'В разработке', disabled: true },
      ],
    },
    footer: {
      headline: <>Ζήτω ο <em>Πόντος.</em></>,
      sub: 'Да здравствует Понт.',
      cta: 'Связаться',
      cols: [
        { h: 'Проект', items: ['Дорожная карта', 'Источники', 'Команда', 'Поддержать'] },
        { h: 'Платформы', items: ['Evera.world', 'Persei.io', 'Библиотека Вечных', 'GitHub'] },
        { h: 'Контакт', items: ['Telegram', 'Maximian Solomonidis', 'Красная Поляна, Сочи', 'Парти, Трапезунд'] },
      ],
      legal: '© Pontos AI · 2026',
      city: 'Trebizond · Krasnaya Polyana',
    },
  },

  en: {
    nav: {
      work: 'Roadmap',
      services: 'Sources',
      about: 'Team',
      contact: 'Support',
      chat: 'Pontos AI',
    },
    hero: {
      coords: 'Εύξεινος Πόντος · 7th c. BC — present',
      label: 'A language preservation project',
      title1: 'Πόντος AI',
      title2: 'Language',
      title3Em: 'Engine',
      title3: '.',
      tagline: 'The digital brain of the Pontic Greek language. 36,000+ words · 2,600 years of history · 20 dialect regions.',
      taglineLabel: '« Ζήτω ο Πόντος » — Long live Pontus',
      cta: 'Talk to Pontos AI',
      ctaSecondary: 'Roadmap',
      scroll: 'Scroll · κύλιση',
    },
    marquee: ['Τραπεζοῦς', 'Sinope', 'Ἀμισός', 'Κερασοῦς', 'Κωνσταντινούπολις', 'Κριμαία', 'Krasnaya Polyana'],
    stats: [
      { num: '36,000+', label: 'Words in the base' },
      { num: '2,600', label: 'Years of history' },
      { num: '20', label: 'Dialect regions' },
      { num: '4', label: 'Alphabets · alph.' },
    ],
    manifesto: {
      label: 'Project architecture · 01',
      title: 'Pontic Greek — ',
      titleEm: 'a living language, digitised.',
      meta: [
        ['Founder', 'Maximian Solomonidis'],
        ['Bases', 'Krasnaya Polyana · Trebizond'],
        ['Platform', 'Persei.io · Evera.world'],
        ['Languages', 'RU · EN · ΕΛ · TR'],
      ],
      paragraphs: [
        <>Pontic Greek carries 2,600 years of heritage — from Black Sea antiquity to the villages of Trebizond, Sinope and the diaspora. We are building the <em>digital brain</em> of the language: dictionary, grammar, etymology and native voices, all in one living system.</>,
        <>The project unites academic dictionaries, folklore archives and AI that answers <em>only</em> from a verified base — no hallucinations. If a word isn't there, the system says so honestly.</>,
      ],
    },
    pillars: {
      label: 'Capabilities · 02',
      title: 'Four pillars,',
      titleEm: 'one language.',
      items: [
        { greek: '📖', name: 'Dictionary', desc: 'Search 36,000+ words. Each card: Greek, Cyrillic, Latin, etymology, dialect, source.' },
        { greek: '🔡', name: 'Any alphabet', desc: 'The system understands Greek, Cyrillic, Latin and Turkish spellings of the same word.' },
        { greek: '🎯', name: 'No fiction', desc: 'AI answers only from the base. If the word is missing it says so honestly. No hallucinations.' },
        { greek: '🚧', name: 'Coming soon', desc: 'Full chat with history, grammar, culture and songs — embedded directly into this site.' },
      ],
    },
    services: {
      label: 'Knowledge base · 03',
      title: 'Literature ',
      titleEm: 'and sources.',
      items: [
        { num: '/01', title: <>Academic <em>dictionaries</em></>, desc: 'Papanikolaou, Andriotis, Opatos — classical lexicographic works on the Pontic dialect.' },
        { num: '/02', title: <>Folklore <em>archives</em></>, desc: 'Songs, proverbs, tales, ritual texts — the voice of the language as it lives in everyday life.' },
        { num: '/03', title: <>Native <em>voices</em></>, desc: 'Field recordings and audio material from villages of Pontus, Caucasus, Greece and the diaspora.' },
        { num: '/04', title: <>Forthcoming <em>editions</em></>, desc: 'New publications, dissertations and archival material being prepared for inclusion.' },
      ],
    },
    work: {
      label: 'Roadmap · 04',
      title: '20 stages from ',
      titleEm: 'archive to dialogue.',
      items: [
        { num: '01', title: <>Source <em>collection</em></>, desc: 'Scanning academic dictionaries, digitising folklore archives and field material.', tags: ['Done', '36k words'] },
        { num: '02', title: <>Cross-<em>alphabet index</em></>, desc: 'Greek, Cyrillic, Latin and Turkish spellings of one word — unified base.', tags: ['Done', 'Search'] },
        { num: '03', title: <>Word <em>card</em></>, desc: 'Translation, etymology, dialect, source and example usage in one view.', tags: ['Done', 'UI'] },
        { num: '04', title: <>Basic <em>AI dialogue</em></>, desc: 'Dictionary Mode: AI answers only from the verified base, no hallucinations.', tags: ['Done', 'AI'] },
        { num: '05', title: <>Etymological <em>chains</em></>, desc: 'Links between Ancient, Medieval and modern Pontic usage.', tags: ['In progress', 'Linguistics'] },
        { num: '06', title: <>Dialect <em>regions</em></>, desc: 'A map of 20 zones — from Trebizond and Sinope to Romeyka and the Caucasus.', tags: ['In progress', 'Map'] },
        { num: '07', title: <>Grammar <em>tables</em></>, desc: 'Conjugations, declensions, morphology of Pontic with examples for every form.', tags: ['In progress', 'Grammar'] },
        { num: '08', title: <>Phraseology and <em>idioms</em></>, desc: 'Set expressions, sayings, politeness formulas and ritual forms.', tags: ['In progress', 'Phrases'] },
        { num: '09', title: <>Voice and <em>audio</em></>, desc: 'Native-spoken cards, songs and phonetics for every dialect.', tags: ['Q3 2026', 'Audio'] },
        { num: '10', title: <>Text <em>corpus</em></>, desc: 'Searchable corpus: folklore, publications, translations — with concordance and contexts.', tags: ['Q3 2026', 'Corpus'] },
        { num: '11', title: <>Songs and <em>μοιρολόγια</em></>, desc: 'Digital archive of Pontic songs with lyrics, translation and audio.', tags: ['Q3 2026', 'Music'] },
        { num: '12', title: <>School <em>module</em></>, desc: 'Interactive lessons, exercises and flashcards for language learners.', tags: ['Q4 2026', 'Education'] },
        { num: '13', title: <>Game <em>trainers</em></>, desc: 'Memory cards, phonetic games, culture mini-quests.', tags: ['Q4 2026', 'Gamified'] },
        { num: '14', title: <>API and <em>SDK</em></>, desc: 'Open API for researchers, schools and cultural projects.', tags: ['Q4 2026', 'Dev'] },
        { num: '15', title: <>Full <em>AI chat</em></>, desc: 'Grammar, culture, songs and free dialogue — embedded into pontos.world.', tags: ['Q4 2026', 'Chat'] },
        { num: '16', title: <>Voice <em>input</em></>, desc: 'Speech recognition for Pontic — search and dialogue by voice.', tags: ['2027', 'Voice'] },
        { num: '17', title: <>Literary <em>publishing</em></>, desc: 'Digital library of books, periodicals and archival publications.', tags: ['2027', 'Library'] },
        { num: '18', title: <>Social <em>layer</em></>, desc: 'Profiles of native speakers and researchers, discussions, collaborative editing.', tags: ['2027', 'Social'] },
        { num: '19', title: <>Mobile <em>apps</em></>, desc: 'iOS and Android: dictionary, chat, trainers and audio — offline access.', tags: ['2027', 'Mobile'] },
        { num: '20', title: <>Living <em>dialogue</em></>, desc: 'Full digital ecosystem: a home for the Pontic language for everyone seeking it.', tags: ['Vision', 'Future'] },
      ],
    },
    chat: {
      label: 'Pontos AI · Dictionary Mode',
      title: 'Talk ',
      titleEm: 'to Pontus.',
      desc: '36,000+ words · Greek · Cyrillic · Latin · Turkish',
      placeholder: 'Enter a word in any alphabet — Russian, Greek, Latin or Turkish',
      examples: ['νερόν', 'water', 'aman', 'Τραπεζοῦς', 'blood', 'αίμαν'],
      cta: 'Open Pontos AI',
    },
    team: {
      label: 'Team · 05',
      title: 'Native speakers, scholars, ',
      titleEm: 'engineers.',
      desc: 'Are you a native speaker, philologist or researcher? Join us — every voice is invaluable.',
      cta: 'Join the project',
    },
    support: {
      label: 'Support · 06',
      title: 'Help the ',
      titleEm: 'project.',
      desc: 'The support section is in development. The best way to help right now is to share the project or reach out directly.',
      items: [
        { icon: '🗣️', title: 'Native speaker', desc: 'Record words, phrases, songs, proverbs — your voice is invaluable.', cta: 'Write' },
        { icon: '🔬', title: 'Researcher', desc: 'Help with data verification, etymology, grammar.', cta: 'Write' },
        { icon: '💛', title: 'Financially', desc: 'Payment module is coming. The project runs on enthusiasm and love for the language.', cta: 'In development', disabled: true },
      ],
    },
    footer: {
      headline: <>Ζήτω ο <em>Πόντος.</em></>,
      sub: 'Long live Pontus.',
      cta: 'Get in touch',
      cols: [
        { h: 'Project', items: ['Roadmap', 'Sources', 'Team', 'Support'] },
        { h: 'Platforms', items: ['Evera.world', 'Persei.io', 'Eternals Library', 'GitHub'] },
        { h: 'Contact', items: ['Telegram', 'Maximian Solomonidis', 'Krasnaya Polyana, Sochi', 'Parti, Trebizond'] },
      ],
      legal: '© Pontos AI · 2026',
      city: 'Trebizond · Krasnaya Polyana',
    },
  },
};

PONTOS_CONTENT.el = {
  nav: { work: 'Πορεία', services: 'Πηγές', about: 'Ομάδα', contact: 'Στήριξη', chat: 'Pontos AI' },
  hero: {
    coords: 'Εύξεινος Πόντος · 7ος αι. π.Χ. — σήμερα',
    label: 'Έργο διάσωσης της γλώσσας',
    title1: 'Πόντος AI',
    title2: 'Language',
    title3Em: 'Engine',
    title3: '.',
    tagline: 'Ο ψηφιακός εγκέφαλος της ποντιακής ελληνικής γλώσσας. 36.000+ λέξεις · 2.600 χρόνια ιστορίας · 20 διαλεκτικές περιοχές.',
    taglineLabel: '« Ζήτω ο Πόντος »',
    cta: 'Μίλα στο Pontos AI',
    ctaSecondary: 'Πορεία',
    scroll: 'Κύλιση · κύλιση',
  },
  marquee: ['Τραπεζοῦς', 'Σινώπη', 'Ἀμισός', 'Κερασοῦς', 'Κωνσταντινούπολις', 'Κριμαία', 'Krasnaya Polyana'],
  stats: [
    { num: '36.000+', label: 'Λέξεις στη βάση' },
    { num: '2.600', label: 'Χρόνια ιστορίας' },
    { num: '20', label: 'Διαλεκτικές περιοχές' },
    { num: '4', label: 'Αλφάβητα · αλφ.' },
  ],
  manifesto: {
    label: 'Αρχιτεκτονική · 01',
    title: 'Ποντιακή ελληνική — ',
    titleEm: 'ζωντανή γλώσσα στην ψηφιακή εποχή.',
    meta: [
      ['Ιδρυτής', 'Maximian Solomonidis'],
      ['Έδρες', 'Krasnaya Polyana · Τραπεζούντα'],
      ['Πλατφόρμα', 'Persei.io · Evera.world'],
      ['Γλώσσες', 'RU · EN · ΕΛ · TR'],
    ],
    paragraphs: [
      <>Η ποντιακή κουβαλά 2.600 χρόνια κληρονομιάς — από την αρχαιότητα του Εύξεινου Πόντου μέχρι τα χωριά της Τραπεζούντας, της Σινώπης και της διασποράς. Χτίζουμε τον <em>ψηφιακό εγκέφαλο</em> της γλώσσας: λεξικό, γραμματική, ετυμολογία και φωνές ομιλητών.</>,
      <>Το έργο ενώνει ακαδημαϊκά λεξικά, λαογραφικά αρχεία και AI που απαντά <em>μόνο</em> από επαληθευμένη βάση — χωρίς ψευδαισθήσεις. Αν η λέξη δεν υπάρχει, το λέει τίμια.</>,
    ],
  },
  pillars: {
    label: 'Δυνατότητες · 02',
    title: 'Τέσσερις στυλοβάτες,',
    titleEm: 'μία γλώσσα.',
    items: [
      { greek: '📖', name: 'Λεξικό', desc: 'Αναζήτηση σε 36.000+ λέξεις. Κάρτα: ελληνικά, κυριλλικά, λατινικά, ετυμολογία, διάλεκτος, πηγή.' },
      { greek: '🔡', name: 'Κάθε αλφάβητο', desc: 'Το σύστημα αναγνωρίζει ελληνική, κυριλλική, λατινική και τουρκική γραφή της ίδιας λέξης.' },
      { greek: '🎯', name: 'Χωρίς εφευρέσεις', desc: 'Το AI απαντά μόνο από τη βάση. Αν λείπει, το παραδέχεται. Καμία ψευδαίσθηση.' },
      { greek: '🚧', name: 'Σύντομα', desc: 'Πλήρες chat με ιστορία, γραμματική, πολιτισμό και τραγούδια — ενσωματωμένο εδώ.' },
    ],
  },
  services: {
    label: 'Βάση γνώσης · 03',
    title: 'Λογοτεχνία ',
    titleEm: 'και πηγές.',
    items: [
      { num: '/01', title: <>Ακαδημαϊκά <em>λεξικά</em></>, desc: 'Παπανικολάου, Ανδριώτης, Όπατος — κλασικά λεξικογραφικά έργα της ποντιακής διαλέκτου.' },
      { num: '/02', title: <>Λαογραφικά <em>αρχεία</em></>, desc: 'Τραγούδια, παροιμίες, παραμύθια, τελετουργικά κείμενα — η φωνή της γλώσσας στην καθημερινότητα.' },
      { num: '/03', title: <>Φωνές <em>ομιλητών</em></>, desc: 'Επιτόπιες ηχογραφήσεις από χωριά του Πόντου, του Καυκάσου, της Ελλάδας και της διασποράς.' },
      { num: '/04', title: <>Επερχόμενες <em>εκδόσεις</em></>, desc: 'Νέες δημοσιεύσεις, διατριβές και αρχειακό υλικό προς ένταξη.' },
    ],
  },
  work: {
    label: 'Πορεία · 04',
    title: '20 στάδια από ',
    titleEm: 'το αρχείο στον διάλογο.',
    items: [
      { num: '01', title: <>Συλλογή <em>πηγών</em></>, desc: 'Σάρωση ακαδημαϊκών λεξικών, ψηφιοποίηση λαογραφικών και επιτόπιων αρχείων.', tags: ['Ολοκληρώθηκε', '36k λέξεις'] },
      { num: '02', title: <>Πολυ-<em>αλφαβητικός δείκτης</em></>, desc: 'Ελληνική, κυριλλική, λατινική και τουρκική γραφή — ενιαίο ευρετήριο.', tags: ['Ολοκληρώθηκε', 'Search'] },
      { num: '03', title: <>Καρτέλα <em>λέξης</em></>, desc: 'Μετάφραση, ετυμολογία, διάλεκτος, πηγή και παραδείγματα σε μία προβολή.', tags: ['Ολοκληρώθηκε', 'UI'] },
      { num: '04', title: <>Βασικός <em>AI διάλογος</em></>, desc: 'Dictionary Mode: το AI απαντά μόνο από επαληθευμένη βάση, χωρίς ψευδαισθήσεις.', tags: ['Ολοκληρώθηκε', 'AI'] },
      { num: '05', title: <>Ετυμολογικές <em>αλυσίδες</em></>, desc: 'Συνδέσεις αρχαίας, μεσαιωνικής και σύγχρονης ποντιακής χρήσης.', tags: ['Σε εξέλιξη', 'Linguistics'] },
      { num: '06', title: <>Διαλεκτικές <em>περιοχές</em></>, desc: 'Χάρτης 20 ζωνών — από Τραπεζούντα και Σινώπη μέχρι Ρωμέικα και Καύκασο.', tags: ['Σε εξέλιξη', 'Map'] },
      { num: '07', title: <>Γραμματικοί <em>πίνακες</em></>, desc: 'Κλίσεις, μορφολογία της ποντιακής με παραδείγματα για κάθε τύπο.', tags: ['Σε εξέλιξη', 'Grammar'] },
      { num: '08', title: <>Φρασεολογία και <em>ιδιωτισμοί</em></>, desc: 'Παγιωμένες εκφράσεις, ρητά, τύποι ευγένειας και τελετουργικές φόρμες.', tags: ['Σε εξέλιξη', 'Phrases'] },
      { num: '09', title: <>Φωνή και <em>ήχος</em></>, desc: 'Καρτέλες με φωνή ομιλητών, τραγούδια και φωνητική για κάθε διάλεκτο.', tags: ['Q3 2026', 'Audio'] },
      { num: '10', title: <>Σώμα <em>κειμένων</em></>, desc: 'Σώμα αναζήτησης: λαογραφία, εκδόσεις, μεταφράσεις — με συμφραζόμενα.', tags: ['Q3 2026', 'Corpus'] },
      { num: '11', title: <>Τραγούδια και <em>μοιρολόγια</em></>, desc: 'Ψηφιακό αρχείο ποντιακών τραγουδιών με στίχους, μετάφραση και ήχο.', tags: ['Q3 2026', 'Music'] },
      { num: '12', title: <>Σχολική <em>ενότητα</em></>, desc: 'Διαδραστικά μαθήματα, ασκήσεις και κάρτες για μαθητές της γλώσσας.', tags: ['Q4 2026', 'Education'] },
      { num: '13', title: <>Παιγνιώδεις <em>ασκήσεις</em></>, desc: 'Κάρτες μνήμης, φωνητικά παιχνίδια, μίνι αποστολές πολιτισμού.', tags: ['Q4 2026', 'Gamified'] },
      { num: '14', title: <>API και <em>SDK</em></>, desc: 'Ανοιχτό API για ερευνητές, σχολεία και πολιτιστικά έργα.', tags: ['Q4 2026', 'Dev'] },
      { num: '15', title: <>Πλήρες <em>AI chat</em></>, desc: 'Γραμματική, πολιτισμός, τραγούδια και ελεύθερος διάλογος — μέσα στο pontos.world.', tags: ['Q4 2026', 'Chat'] },
      { num: '16', title: <>Φωνητική <em>είσοδος</em></>, desc: 'Αναγνώριση ποντιακής ομιλίας — αναζήτηση και διάλογος με τη φωνή.', tags: ['2027', 'Voice'] },
      { num: '17', title: <>Λογοτεχνικές <em>εκδόσεις</em></>, desc: 'Ψηφιακή βιβλιοθήκη βιβλίων, περιοδικών και αρχειακών εκδόσεων.', tags: ['2027', 'Library'] },
      { num: '18', title: <>Κοινωνικό <em>επίπεδο</em></>, desc: 'Προφίλ ομιλητών και ερευνητών, συζητήσεις, συνεργατική επιμέλεια.', tags: ['2027', 'Social'] },
      { num: '19', title: <>Κινητές <em>εφαρμογές</em></>, desc: 'iOS και Android: λεξικό, chat, ασκήσεις και ήχος — πρόσβαση offline.', tags: ['2027', 'Mobile'] },
      { num: '20', title: <>Ζωντανός <em>διάλογος</em></>, desc: 'Πλήρες ψηφιακό οικοσύστημα: σπίτι της ποντιακής για κάθε αναζητητή.', tags: ['Vision', 'Future'] },
    ],
  },
  chat: {
    label: 'Pontos AI · Dictionary Mode',
    title: 'Μίλα ',
    titleEm: 'με τον Πόντο.',
    desc: '36.000+ λέξεις · Ελληνικά · Κυριλλικά · Λατινικά · Τουρκικά',
    placeholder: 'Πληκτρολογήστε μια λέξη σε οποιοδήποτε αλφάβητο — ελληνικό, κυριλλικό, λατινικό ή τουρκικό',
    examples: ['νερόν', 'νερό', 'aman', 'Τραπεζοῦς', 'αίμα', 'αίμαν'],
    cta: 'Άνοιγμα Pontos AI',
  },
  team: {
    label: 'Ομάδα · 05',
    title: 'Ομιλητές, ερευνητές, ',
    titleEm: 'μηχανικοί.',
    desc: 'Είστε ομιλητής, φιλόλογος ή ερευνητής; Ελάτε μαζί μας — κάθε φωνή είναι ανεκτίμητη.',
    cta: 'Συμμετοχή στο έργο',
  },
  support: {
    label: 'Στήριξη · 06',
    title: 'Βοηθήστε ',
    titleEm: 'το έργο.',
    desc: 'Η ενότητα στήριξης είναι υπό κατασκευή. Προς το παρόν, μοιραστείτε το έργο ή επικοινωνήστε απευθείας.',
    items: [
      { icon: '🗣️', title: 'Ομιλητής', desc: 'Καταγράψτε λέξεις, φράσεις, τραγούδια, παροιμίες — η φωνή σας είναι ανεκτίμητη.', cta: 'Γράψτε' },
      { icon: '🔬', title: 'Ερευνητής', desc: 'Βοηθήστε με επαλήθευση δεδομένων, ετυμολογία, γραμματική.', cta: 'Γράψτε' },
      { icon: '💛', title: 'Οικονομικά', desc: 'Σύντομα module πληρωμών. Το έργο τρέχει με ενθουσιασμό και αγάπη για τη γλώσσα.', cta: 'Υπό ανάπτυξη', disabled: true },
    ],
  },
  footer: {
    headline: <>Ζήτω ο <em>Πόντος.</em></>,
    sub: 'Long live Pontus.',
    cta: 'Επικοινωνία',
    cols: [
      { h: 'Έργο', items: ['Πορεία', 'Πηγές', 'Ομάδα', 'Στήριξη'] },
      { h: 'Πλατφόρμες', items: ['Evera.world', 'Persei.io', 'Eternals Library', 'GitHub'] },
      { h: 'Επαφή', items: ['Telegram', 'Maximian Solomonidis', 'Krasnaya Polyana, Sochi', 'Parti, Trebizond'] },
    ],
    legal: '© Pontos AI · 2026',
    city: 'Trebizond · Krasnaya Polyana',
  },
};

PONTOS_CONTENT.tr = {
  nav: { work: 'Yol haritası', services: 'Kaynaklar', about: 'Ekip', contact: 'Destek', chat: 'Pontos AI' },
  hero: {
    coords: 'Karadeniz · MÖ 7. yy — günümüz',
    label: 'Bir dil koruma projesi',
    title1: 'Πόντος AI',
    title2: 'Language',
    title3Em: 'Engine',
    title3: '.',
    tagline: 'Pontus Rumcasının dijital beyni. 36.000+ kelime · 2.600 yıllık tarih · 20 lehçe bölgesi.',
    taglineLabel: '« Ζήτω ο Πόντος » — Yaşasın Pontus',
    cta: "Pontos AI ile konuş",
    ctaSecondary: 'Yol haritası',
    scroll: 'Kaydır · κύλιση',
  },
  marquee: ['Trabzon', 'Sinop', 'Samsun', 'Giresun', 'İstanbul', 'Kırım', 'Krasnaya Polyana'],
  stats: [
    { num: '36.000+', label: "Veritabanındaki kelime" },
    { num: '2.600', label: 'Yıllık tarih' },
    { num: '20', label: 'Lehçe bölgesi' },
    { num: '4', label: 'Alfabe · alf.' },
  ],
  manifesto: {
    label: 'Proje mimarisi · 01',
    title: 'Pontus Rumcası — ',
    titleEm: 'dijitalleşen yaşayan bir dil.',
    meta: [
      ['Kurucu', 'Maximian Solomonidis'],
      ['Merkezler', 'Krasnaya Polyana · Trabzon'],
      ['Platform', 'Persei.io · Evera.world'],
      ['Diller', 'RU · EN · ΕΛ · TR'],
    ],
    paragraphs: [
      <>Pontus Rumcası 2.600 yıllık bir mirası taşır — Karadeniz antik çağından Trabzon, Sinop ve diasporanın köylerine. Dilin <em>dijital beynini</em> inşa ediyoruz: sözlük, dilbilgisi, etimoloji ve anadil seslerini tek bir yaşayan sistemde.</>,
      <>Proje, akademik sözlükleri, folklor arşivlerini ve <em>yalnızca</em> doğrulanmış veriden cevap veren bir AI'ı bir araya getirir — uydurma yok. Kelime yoksa, sistem dürüstçe söyler.</>,
    ],
  },
  pillars: {
    label: 'Yetenekler · 02',
    title: 'Dört sütun,',
    titleEm: 'tek dil.',
    items: [
      { greek: '📖', name: 'Sözlük', desc: '36.000+ kelimede arama. Kart: Yunan, Kiril, Latin, etimoloji, lehçe, kaynak.' },
      { greek: '🔡', name: 'Her alfabe', desc: 'Sistem aynı kelimenin Yunan, Kiril, Latin ve Türk yazımını anlar.' },
      { greek: '🎯', name: 'Uydurma yok', desc: 'AI sadece veritabanından yanıt verir. Kelime yoksa dürüstçe söyler. Halüsinasyon yok.' },
      { greek: '🚧', name: 'Yakında', desc: 'Tarih, dilbilgisi, kültür ve şarkılarla tam sohbet — doğrudan bu siteye gömülü.' },
    ],
  },
  services: {
    label: 'Bilgi tabanı · 03',
    title: 'Edebiyat ',
    titleEm: 've kaynaklar.',
    items: [
      { num: '/01', title: <>Akademik <em>sözlükler</em></>, desc: 'Papanikolaou, Andriotis, Opatos — Pontus lehçesi üzerine klasik sözlük çalışmaları.' },
      { num: '/02', title: <>Folklor <em>arşivleri</em></>, desc: 'Şarkılar, atasözleri, masallar, ritüel metinler — dilin günlük yaşamdaki sesi.' },
      { num: '/03', title: <>Anadil <em>sesleri</em></>, desc: 'Pontus, Kafkasya, Yunanistan ve diaspora köylerinden saha kayıtları.' },
      { num: '/04', title: <>Beklenen <em>baskılar</em></>, desc: 'Yeni yayınlar, tezler ve eklenmek üzere hazırlanan arşiv materyali.' },
    ],
  },
  work: {
    label: 'Yol haritası · 04',
    title: 'Arşivden diyaloga ',
    titleEm: '20 aşama.',
    items: [
      { num: '01', title: <>Kaynak <em>toplama</em></>, desc: 'Akademik sözlüklerin taranması, folklor ve saha materyallerinin dijitalleştirilmesi.', tags: ['Tamam', '36k kelime'] },
      { num: '02', title: <>Çapraz-<em>alfabe dizini</em></>, desc: 'Bir kelimenin Yunan, Kiril, Latin ve Türk yazımı — birleşik veri tabanı.', tags: ['Tamam', 'Search'] },
      { num: '03', title: <>Kelime <em>kartı</em></>, desc: 'Çeviri, etimoloji, lehçe, kaynak ve örnek kullanımı tek bir görünümde.', tags: ['Tamam', 'UI'] },
      { num: '04', title: <>Temel <em>AI diyaloğu</em></>, desc: "Dictionary Mode: AI yalnızca doğrulanmış veritabanından yanıt verir, halüsinasyon yok.", tags: ['Tamam', 'AI'] },
      { num: '05', title: <>Etimolojik <em>zincirler</em></>, desc: 'Antik, Orta Çağ ve modern Pontus kullanımı arasındaki bağlantılar.', tags: ['Sürüyor', 'Linguistics'] },
      { num: '06', title: <>Lehçe <em>bölgeleri</em></>, desc: "Trabzon ve Sinop'tan Romeyka ve Kafkasya'ya kadar 20 bölgenin haritası.", tags: ['Sürüyor', 'Map'] },
      { num: '07', title: <>Dilbilgisi <em>tabloları</em></>, desc: 'Pontus dilinin çekimleri ve morfolojisi, her form için örneklerle.', tags: ['Sürüyor', 'Grammar'] },
      { num: '08', title: <>Deyim ve <em>kalıplar</em></>, desc: 'Kalıp ifadeler, atasözleri, nezaket formülleri ve ritüel formlar.', tags: ['Sürüyor', 'Phrases'] },
      { num: '09', title: <>Ses ve <em>kayıt</em></>, desc: 'Anadil seslendirmesi, şarkılar ve her lehçe için fonetik.', tags: ['Q3 2026', 'Audio'] },
      { num: '10', title: <>Metin <em>derlemi</em></>, desc: 'Aranabilir derlem: folklor, yayınlar, çeviriler — konkordans ve bağlamlarla.', tags: ['Q3 2026', 'Corpus'] },
      { num: '11', title: <>Şarkılar ve <em>μοιρολόγια</em></>, desc: 'Pontus şarkılarının dijital arşivi — sözler, çeviri ve ses.', tags: ['Q3 2026', 'Music'] },
      { num: '12', title: <>Okul <em>modülü</em></>, desc: 'Dil öğrenenler için interaktif dersler, alıştırmalar ve kartlar.', tags: ['Q4 2026', 'Education'] },
      { num: '13', title: <>Oyunlaştırılmış <em>antrenmanlar</em></>, desc: 'Hafıza kartları, fonetik oyunlar, kültür mini görevleri.', tags: ['Q4 2026', 'Gamified'] },
      { num: '14', title: <>API ve <em>SDK</em></>, desc: 'Araştırmacılar, okullar ve kültür projeleri için açık API.', tags: ['Q4 2026', 'Dev'] },
      { num: '15', title: <>Tam <em>AI sohbet</em></>, desc: "Dilbilgisi, kültür, şarkılar ve serbest diyalog — pontos.world'e gömülü.", tags: ['Q4 2026', 'Chat'] },
      { num: '16', title: <>Sesli <em>giriş</em></>, desc: 'Pontus dili için konuşma tanıma — sesle arama ve diyalog.', tags: ['2027', 'Voice'] },
      { num: '17', title: <>Edebi <em>yayıncılık</em></>, desc: 'Kitaplar, süreli yayınlar ve arşiv yayınlarının dijital kütüphanesi.', tags: ['2027', 'Library'] },
      { num: '18', title: <>Sosyal <em>katman</em></>, desc: 'Anadil konuşurları ve araştırmacıların profilleri, tartışmalar, ortak düzenleme.', tags: ['2027', 'Social'] },
      { num: '19', title: <>Mobil <em>uygulamalar</em></>, desc: 'iOS ve Android: sözlük, sohbet, antrenmanlar ve ses — çevrimdışı erişim.', tags: ['2027', 'Mobile'] },
      { num: '20', title: <>Yaşayan <em>diyalog</em></>, desc: 'Tam dijital ekosistem: dili arayan herkes için Pontus dilinin evi.', tags: ['Vision', 'Future'] },
    ],
  },
  chat: {
    label: 'Pontos AI · Dictionary Mode',
    title: "Pontus ile ",
    titleEm: 'konuş.',
    desc: '36.000+ kelime · Yunan · Kiril · Latin · Türk',
    placeholder: 'Herhangi bir alfabede bir kelime girin — Rusça, Yunanca, Latince veya Türkçe',
    examples: ['νερόν', 'su', 'aman', 'Τραπεζοῦς', 'kan', 'αίμαν'],
    cta: "Pontos AI'ı aç",
  },
  team: {
    label: 'Ekip · 05',
    title: 'Anadil konuşurları, akademisyenler, ',
    titleEm: 'mühendisler.',
    desc: 'Anadil konuşuru, filolog veya araştırmacı mısınız? Bize katılın — her ses paha biçilmez.',
    cta: 'Projeye katıl',
  },
  support: {
    label: 'Destek · 06',
    title: 'Projeye ',
    titleEm: 'yardım edin.',
    desc: 'Destek bölümü geliştiriliyor. Şu an en iyi yardım — projeyi paylaşmak veya doğrudan iletişime geçmek.',
    items: [
      { icon: '🗣️', title: 'Anadil konuşuru', desc: 'Kelimeleri, deyimleri, şarkıları, atasözlerini kaydedin — sesiniz paha biçilmezdir.', cta: 'Yaz' },
      { icon: '🔬', title: 'Araştırmacı', desc: 'Veri doğrulama, etimoloji, dilbilgisi konularında yardım edin.', cta: 'Yaz' },
      { icon: '💛', title: 'Maddi', desc: 'Ödeme modülü yakında. Proje, dile duyulan sevgi ve coşkuyla yürüyor.', cta: 'Geliştirme aşamasında', disabled: true },
    ],
  },
  footer: {
    headline: <>Ζήτω ο <em>Πόντος.</em></>,
    sub: 'Yaşasın Pontus.',
    cta: 'İletişim',
    cols: [
      { h: 'Proje', items: ['Yol haritası', 'Kaynaklar', 'Ekip', 'Destek'] },
      { h: 'Platformlar', items: ['Evera.world', 'Persei.io', 'Eternals Library', 'GitHub'] },
      { h: 'İletişim', items: ['Telegram', 'Maximian Solomonidis', 'Krasnaya Polyana, Soçi', 'Parti, Trabzon'] },
    ],
    legal: '© Pontos AI · 2026',
    city: 'Trabzon · Krasnaya Polyana',
  },
};

window.PONTOS_CONTENT = PONTOS_CONTENT;
