/* ============ Pontos AI: Real bilingual content (RU/EN) ============ */

const PONTOS_CONTENT = {
  ru: {
    nav: {
      work: 'Дорожная карта',
      services: 'Источники',
      about: 'Команда',
      contact: 'Поддержать',
      chat: 'Pontos AI',
    },
    hero: {
      coords: 'Εύξεινος Πόντος · VII в. до н.э. — наши дни',
      label: 'Проект сохранения языка',
      title1: 'Πόντος AI',
      title2: 'Language',
      title3Em: 'Engine',
      title3: '.',
      tagline: 'Цифровой мозг понтийского греческого языка. 36 000+ слов · 2 600 лет истории · 20 диалектных регионов.',
      taglineLabel: '« Ζήτω ο Πόντος » — Да здравствует Понт',
      cta: 'Поговорить с Pontos AI',
      ctaSecondary: 'Дорожная карта',
      scroll: 'Прокрутить · κύλιση',
    },
    marquee: ['Τραπεζοῦς', 'Sinope', 'Ἀμισός', 'Κερασοῦς', 'Κωνσταντινούπολις', 'Κριμαία', 'Красная Поляна'],
    stats: [
      { num: '36 000+', label: 'Слов в базе' },
      { num: '2 600', label: 'Лет истории' },
      { num: '20', label: 'Диалектных регионов' },
      { num: '4', label: 'Алфавита · алф.' },
    ],
    manifesto: {
      label: 'Архитектура проекта · 01',
      title: 'Понтийский греческий — ',
      titleEm: 'живой язык в цифре.',
      meta: [
        ['Статус', 'В разработке'],
        ['База', '36 000+ слов'],
        ['Платформа', 'Persei.io · Evera.world'],
        ['Языки', 'RU · EN · ΕΛ · TR'],
      ],
      paragraphs: [
        <>Понтийский — наследие 2 600 лет, от черноморских колоний античности до сёл Трапезунда, Синопа и диаспоры. Мы строим <em>цифровой мозг</em> языка: словари, грамматику, этимологию и голоса носителей в одной живой системе.</>,
        <>Проект объединяет академические словари, фольклорные архивы и AI, который отвечает <em>только</em> из проверенной базы — без выдумок. Если слова нет — система говорит об этом честно.</>,
      ],
    },
    pillars: {
      label: 'Возможности · 02',
      title: 'Четыре опоры,',
      titleEm: 'один язык.',
      items: [
        { greek: '📖', name: 'Словарь', desc: 'Поиск по 36 000+ словам. Карточка слова: греческий, кириллица, латиница, этимология, диалект, источник.' },
        { greek: '🔡', name: 'Алфавиты', desc: 'Система понимает греческое, кириллическое, латинское и турецкое написание одного слова.' },
        { greek: '🎯', name: 'Без выдумок', desc: 'AI отвечает только из базы. Если слова нет — говорит об этом честно. Никаких галлюцинаций.' },
        { greek: '🚧', name: 'Скоро', desc: 'Полный чат с историей, грамматикой, культурой и песнями — встраивается прямо в этот сайт.' },
      ],
    },
    services: {
      label: 'База знаний · 03',
      title: 'Литература ',
      titleEm: 'и источники.',
      items: [
        { num: '/01', title: <>Академические <em>словари</em></>, desc: 'Папаниколау, Андриотис, Опатос — классические лексикографические труды по понтийскому диалекту.' },
        { num: '/02', title: <>Фольклорные <em>архивы</em></>, desc: 'Песни, пословицы, сказки, обрядовые тексты — голос языка, как он звучит в быту.' },
        { num: '/03', title: <>Голоса <em>носителей</em></>, desc: 'Полевые записи и аудиоматериалы из сёл Понта, Кавказа, Греции и диаспоры.' },
        { num: '/04', title: <>Ожидаемые <em>издания</em></>, desc: 'Новые публикации, диссертации и архивные материалы, готовящиеся к включению в базу.' },
      ],
    },
    work: {
      label: 'Дорожная карта · 04',
      title: '20 этапов от ',
      titleEm: 'архива до диалога.',
      items: window.ROADMAP_DATA.ru,
    },
    chat: {
      label: 'Pontos AI · Dictionary Mode',
      title: 'Поговорить ',
      titleEm: 'с Понтом.',
      desc: '36 000+ слов · Греческий · Кириллица · Латиница · Турецкий',
      placeholder: 'Введите слово на любом алфавите — русском, греческом, латинском или турецком',
      examples: ['νερόν', 'вода', 'aman', 'Τραπεζοῦς', 'кровь', 'αίμαν'],
      cta: 'Открыть Pontos AI',
    },
    team: {
      label: 'Команда · 05',
      title: 'Носители, учёные, ',
      titleEm: 'инженеры.',
      desc: 'Вы носитель языка, филолог или исследователь? Присоединяйтесь — каждый голос бесценен.',
      items: [
        { name: 'Максимиан Соломонидис', role: 'Ai-инженер, основатель Persei.io & Evera.world, создатель "Библиотеки вечных".', link: 'https://persei.io/?start=ref_solo013-eternals' },
        { name: 'Михаил Катанов', role: 'Носитель языка, исследователь.' },
        { name: 'Константин Кесов', role: 'Председатель КГОО «Греческая национально-культурная автономия "Ромиосини"»', link: 'https://romiosini.ru/' },
        { name: 'Иван Ананиади', role: 'Руководитель греческого общества "Патрида", Красная Поляна, Сочи', link: 'https://rusgreek.ru/krasnaya-polyanaundefinedsochinskaya-gorodskaya-obschestvennaya-organizatsiya' },
      ],
      cta: 'Присоединиться к проекту',
    },
    support: {
      label: 'Поддержать · 06',
      title: 'Помочь ',
      titleEm: 'проекту.',
      desc: 'Раздел поддержки в разработке. Сейчас лучший способ помочь — поделиться проектом или связаться напрямую.',
      items: [
        { icon: '🗣️', title: 'Носитель языка', desc: 'Запишите слова, фразы, песни, пословицы — ваш голос бесценен.', cta: 'Написать' },
        { icon: '🔬', title: 'Исследователь', desc: 'Помогите с проверкой данных, этимологией, грамматикой.', cta: 'Написать' },
        { icon: '💛', title: 'Финансово', desc: 'Платёжный модуль скоро. Проект строится на энтузиазме и любви к языку.', cta: 'В разработке', disabled: true },
      ],
    },
    footer: {
      headline: <>Ζήτω ο <em>Πόντος.</em></>,
      sub: 'Да здравствует Понт.',
      cta: 'Связаться',
      cols: [
        { h: 'Проект', items: ['Дорожная карта', 'Источники', 'Команда', 'Поддержать'] },
        { h: 'Платформы', items: ['Evera.world', 'Persei.io', 'Библиотека Вечных', 'GitHub'] },
        { h: 'Контакт', items: ['Telegram'] },
      ],
      legal: '© Pontos AI · 2026',
      city: 'Trebizond',
    },
  },

  en: {
    nav: {
      work: 'Roadmap',
      services: 'Sources',
      about: 'Team',
      contact: 'Support',
      chat: 'Pontos AI',
    },
    hero: {
      coords: 'Εύξεινος Πόντος · 7th c. BC — present',
      label: 'A language preservation project',
      title1: 'Πόντος AI',
      title2: 'Language',
      title3Em: 'Engine',
      title3: '.',
      tagline: 'The digital brain of the Pontic Greek language. 36,000+ words · 2,600 years of history · 20 dialect regions.',
      taglineLabel: '« Ζήτω ο Πόντος » — Long live Pontus',
      cta: 'Talk to Pontos AI',
      ctaSecondary: 'Roadmap',
      scroll: 'Scroll · κύλιση',
    },
    marquee: ['Τραπεζοῦς', 'Sinope', 'Ἀμισός', 'Κερασοῦς', 'Κωνσταντινούπολις', 'Κριμαία', 'Krasnaya Polyana'],
    stats: [
      { num: '36,000+', label: 'Words in the base' },
      { num: '2,600', label: 'Years of history' },
      { num: '20', label: 'Dialect regions' },
      { num: '4', label: 'Alphabets · alph.' },
    ],
    manifesto: {
      label: 'Project architecture · 01',
      title: 'Pontic Greek — ',
      titleEm: 'a living language, digitised.',
      meta: [
        ['Founder', 'Maximian Solomonidis'],
        ['Bases', 'Krasnaya Polyana · Trebizond'],
        ['Platform', 'Persei.io · Evera.world'],
        ['Languages', 'RU · EN · ΕΛ · TR'],
      ],
      paragraphs: [
        <>Pontic Greek carries 2,600 years of heritage — from Black Sea antiquity to the villages of Trebizond, Sinope and the diaspora. We are building the <em>digital brain</em> of the language: dictionary, grammar, etymology and native voices, all in one living system.</>,
        <>The project unites academic dictionaries, folklore archives and AI that answers <em>only</em> from a verified base — no hallucinations. If a word isn't there, the system says so honestly.</>,
      ],
    },
    pillars: {
      label: 'Capabilities · 02',
      title: 'Four pillars,',
      titleEm: 'one language.',
      items: [
        { greek: '📖', name: 'Dictionary', desc: 'Search 36,000+ words. Each card: Greek, Cyrillic, Latin, etymology, dialect, source.' },
        { greek: '🔡', name: 'Any alphabet', desc: 'The system understands Greek, Cyrillic, Latin and Turkish spellings of the same word.' },
        { greek: '🎯', name: 'No fiction', desc: 'AI answers only from the base. If the word is missing it says so honestly. No hallucinations.' },
        { greek: '🚧', name: 'Coming soon', desc: 'Full chat with history, grammar, culture and songs — embedded directly into this site.' },
      ],
    },
    services: {
      label: 'Knowledge base · 03',
      title: 'Literature ',
      titleEm: 'and sources.',
      items: [
        { num: '/01', title: <>Academic <em>dictionaries</em></>, desc: 'Papanikolaou, Andriotis, Opatos — classical lexicographic works on the Pontic dialect.' },
        { num: '/02', title: <>Folklore <em>archives</em></>, desc: 'Songs, proverbs, tales, ritual texts — the voice of the language as it lives in everyday life.' },
        { num: '/03', title: <>Native <em>voices</em></>, desc: 'Field recordings and audio material from villages of Pontus, Caucasus, Greece and the diaspora.' },
        { num: '/04', title: <>Forthcoming <em>editions</em></>, desc: 'New publications, dissertations and archival material being prepared for inclusion.' },
      ],
    },
    work: {
      label: 'Roadmap · 04',
      title: '20 stages from ',
      titleEm: 'archive to dialogue.',
      items: window.ROADMAP_DATA.en,
    },
    chat: {
      label: 'Pontos AI · Dictionary Mode',
      title: 'Talk ',
      titleEm: 'to Pontus.',
      desc: '36,000+ words · Greek · Cyrillic · Latin · Turkish',
      placeholder: 'Enter a word in any alphabet — Russian, Greek, Latin or Turkish',
      examples: ['νερόν', 'water', 'aman', 'Τραπεζοῦς', 'blood', 'αίμαν'],
      cta: 'Open Pontos AI',
    },
    team: {
      label: 'Team · 05',
      title: 'Native speakers, scholars, ',
      titleEm: 'engineers.',
      desc: 'Are you a native speaker, philologist or researcher? Join us — every voice is invaluable.',
      items: [
        { name: 'Maximian Solomonidis', role: 'AI Engineer, Founder of Persei.io & Evera.world, Creator of "The Library of Eternals".', link: 'https://persei.io/?start=ref_solo013-eternals' },
        { name: 'Mikhail Katanov', role: 'Native speaker, researcher.' },
        { name: 'Konstantin Kesov', role: 'Head of KRGOO "Greek National-Cultural Autonomy Romiosini"', link: 'https://romiosini.ru/' },
        { name: 'Ivan Ananiadi', role: 'Head of Greek Society "Patrida", Krasnaya Polyana, Sochi', link: 'https://rusgreek.ru/krasnaya-polyanaundefinedsochinskaya-gorodskaya-obschestvennaya-organizatsiya' },
      ],
      cta: 'Join the project',
    },
    support: {
      label: 'Support · 06',
      title: 'Help the ',
      titleEm: 'project.',
      desc: 'The support section is in development. The best way to help right now is to share the project or reach out directly.',
      items: [
        { icon: '🗣️', title: 'Native speaker', desc: 'Record words, phrases, songs, proverbs — your voice is invaluable.', cta: 'Write' },
        { icon: '🔬', title: 'Researcher', desc: 'Help with data verification, etymology, grammar.', cta: 'Write' },
        { icon: '💛', title: 'Financially', desc: 'Payment module is coming. The project runs on enthusiasm and love for the language.', cta: 'In development', disabled: true },
      ],
    },
    footer: {
      headline: <>Ζήτω ο <em>Πόντος.</em></>,
      sub: 'Long live Pontus.',
      cta: 'Get in touch',
      cols: [
        { h: 'Project', items: ['Roadmap', 'Sources', 'Team', 'Support'] },
        { h: 'Platforms', items: ['Evera.world', 'Persei.io', 'Eternals Library', 'GitHub'] },
        { h: 'Contact', items: ['Telegram', 'Maximian Solomonidis', 'Krasnaya Polyana, Sochi'] },
      ],
      legal: '© Pontos AI · 2026',
      city: 'Trebizond · Krasnaya Polyana',
    },
  },
};

PONTOS_CONTENT.el = {
  nav: { work: 'Πορεία', services: 'Πηγές', about: 'Ομάδα', contact: 'Στήριξη', chat: 'Pontos AI' },
  hero: {
    coords: 'Εύξεινος Πόντος · 7ος αι. π.Χ. — σήμερα',
    label: 'Έργο διάσωσης της γλώσσας',
    title1: 'Πόντος AI',
    title2: 'Language',
    title3Em: 'Engine',
    title3: '.',
    tagline: 'Ο ψηφιακός εγκέφαλος της ποντιακής ελληνικής γλώσσας. 36.000+ λέξεις · 2.600 χρόνια ιστορίας · 20 διαλεκτικές περιοχές.',
    taglineLabel: '« Ζήτω ο Πόντος »',
    cta: 'Μίλα στο Pontos AI',
    ctaSecondary: 'Πορεία',
    scroll: 'Κύλιση · κύλιση',
  },
  marquee: ['Τραπεζοῦς', 'Σινώπη', 'Ἀμισός', 'Κερασοῦς', 'Κωνσταντινούπολις', 'Κριμαία', 'Krasnaya Polyana'],
  stats: [
    { num: '36.000+', label: 'Λέξεις στη βάση' },
    { num: '2.600', label: 'Χρόνια ιστορίας' },
    { num: '20', label: 'Διαλεκτικές περιοχές' },
    { num: '4', label: 'Αλφάβητα · αλφ.' },
  ],
  manifesto: {
    label: 'Αρχιτεκτονική · 01',
    title: 'Ποντιακή ελληνική — ',
    titleEm: 'ζωντανή γλώσσα στην ψηφιακή εποχή.',
    meta: [
      ['Ιδρυτής', 'Maximian Solomonidis'],
      ['Έδρες', 'Krasnaya Polyana · Τραπεζούντα'],
      ['Πλατφόρμα', 'Persei.io · Evera.world'],
      ['Γλώσσες', 'RU · EN · ΕΛ · TR'],
    ],
    paragraphs: [
      <>Η ποντιακή κουβαλά 2.600 χρόνια κληρονομιάς — από την αρχαιότητα του Εύξεινου Πόντου μέχρι τα χωριά της Τραπεζούντας, της Σινώπης και της διασποράς. Χτίζουμε τον <em>ψηφιακό εγκέφαλο</em> της γλώσσας: λεξικό, γραμματική, ετυμολογία και φωνές ομιλητών.</>,
      <>Το έργο ενώνει ακαδημαϊκά λεξικά, λαογραφικά αρχεία και AI που απαντά <em>μόνο</em> από επαληθευμένη βάση — χωρίς ψευδαισθήσεις. Αν η λέξη δεν υπάρχει, το λέει τίμια.</>,
    ],
  },
  pillars: {
    label: 'Δυνατότητες · 02',
    title: 'Τέσσερις στυλοβάτες,',
    titleEm: 'μία γλώσσα.',
    items: [
      { greek: '📖', name: 'Λεξικό', desc: 'Αναζήτηση σε 36.000+ λέξεις. Κάρτα: ελληνικά, κυριλλικά, λατινικά, ετυμολογία, διάλεκτος, πηγή.' },
      { greek: '🔡', name: 'Κάθε αλφάβητο', desc: 'Το σύστημα αναγνωρίζει ελληνική, κυριλλική, λατινική και τουρκική γραφή της ίδιας λέξης.' },
      { greek: '🎯', name: 'Χωρίς εφευρέσεις', desc: 'Το AI απαντά μόνο από τη βάση. Αν λείπει, το παραδέχεται. Καμία ψευδαίσθηση.' },
      { greek: '🚧', name: 'Σύντομα', desc: 'Πλήρες chat με ιστορία, γραμματική, πολιτισμό και τραγούδια — ενσωματωμένο εδώ.' },
    ],
  },
  services: {
    label: 'Βάση γνώσης · 03',
    title: 'Λογοτεχνία ',
    titleEm: 'και πηγές.',
    items: [
      { num: '/01', title: <>Ακαδημαϊκά <em>λεξικά</em></>, desc: 'Παπανικολάου, Ανδριώτης, Όπατος — κλασικά λεξικογραφικά έργα της ποντιακής διαλέκτου.' },
      { num: '/02', title: <>Λαογραφικά <em>αρχεία</em></>, desc: 'Τραγούδια, παροιμίες, παραμύθια, τελετουργικά κείμενα — η φωνή της γλώσσας στην καθημερινότητα.' },
      { num: '/03', title: <>Φωνές <em>ομιλητών</em></>, desc: 'Επιτόπιες ηχογραφήσεις από χωριά του Πόντου, του Καυκάσου, της Ελλάδας και της διασποράς.' },
      { num: '/04', title: <>Επερχόμενες <em>εκδόσεις</em></>, desc: 'Νέες δημοσιεύσεις, διατριβές και αρχειακό υλικό προς ένταξη.' },
    ],
  },
  work: {
    label: 'Πορεία · 04',
    title: '20 στάδια από ',
    titleEm: 'το αρχείο στον διάλογο.',
    items: window.ROADMAP_DATA.el,
  },
  chat: {
    label: 'Pontos AI · Dictionary Mode',
    title: 'Μίλα ',
    titleEm: 'με τον Πόντο.',
    desc: '36.000+ λέξεις · Ελληνικά · Κυριλλικά · Λατινικά · Τουρκικά',
    placeholder: 'Πληκτρολογήστε μια λέξη σε οποιοδήποτε αλφάβητο — ελληνικό, κυριλλικό, λατινικό ή τουρκικό',
    examples: ['νερόν', 'νερό', 'aman', 'Τραπεζοῦς', 'αίμα', 'αίμαν'],
    cta: 'Άνοιγμα Pontos AI',
  },
  team: {
    label: 'Ομάδα · 05',
    title: 'Ομιλητές, ερευνητές, ',
    titleEm: 'μηχανικοί.',
    desc: 'Είστε ομιλητής, φιλόλογος ή ερευνητής; Ελάτε μαζί μας — κάθε φωνή είναι ανεκτίμητη.',
    items: [
      { name: 'Μαξιμιανός Σολομωνίδης', role: 'Μηχανικός AI, Ιδρυτής Persei.io & Evera.world, Δημιουργός της "Βιβλιοθήκης των Αιωνίων".', link: 'https://persei.io/?start=ref_solo013-eternals' },
      { name: 'Μιχαήλ Κατάνωφ', role: 'Φυσικός ομιλητής, ερευνητής.' },
      { name: 'Κωνσταντίνος Κέσωφ', role: 'Πρόεδρος KRGOO "Ελληνική Εθνικο-Πολιτιστική Αυτονομία Ρωμιοσύνη"', link: 'https://romiosini.ru/' },
      { name: 'Ιβάν Ανανιάδη', role: 'Επικεφαλής Ελληνικής Κοινότητας "Πατρίδα", Κράσναγια Πολιάνα, Σότσι', link: 'https://rusgreek.ru/krasnaya-polyanaundefinedsochinskaya-gorodskaya-obschestvennaya-organizatsiya' },
    ],
    cta: 'Συμμετοχή στο έργο',
  },
  support: {
    label: 'Στήριξη · 06',
    title: 'Βοηθήστε ',
    titleEm: 'το έργο.',
    desc: 'Η ενότητα στήριξης είναι υπό κατασκευή. Προς το παρόν, μοιραστείτε το έργο ή επικοινωνήστε απευθείας.',
    items: [
      { icon: '🗣️', title: 'Ομιλητής', desc: 'Καταγράψτε λέξεις, φράσεις, τραγούδια, παροιμίες — η φωνή σας είναι ανεκτίμητη.', cta: 'Γράψτε' },
      { icon: '🔬', title: 'Ερευνητής', desc: 'Βοηθήστε με επαλήθευση δεδομένων, ετυμολογία, γραμματική.', cta: 'Γράψτε' },
      { icon: '💛', title: 'Οικονομικά', desc: 'Σύντομα module πληρωμών. Το έργο τρέχει με ενθουσιασμό και αγάπη για τη γλώσσα.', cta: 'Υπό ανάπτυξη', disabled: true },
    ],
  },
  footer: {
    headline: <>Ζήτω ο <em>Πόντος.</em></>,
    sub: 'Long live Pontus.',
    cta: 'Επικοινωνία',
    cols: [
      { h: 'Έργο', items: ['Πορεία', 'Πηγές', 'Ομάδα', 'Στήριξη'] },
      { h: 'Πλατφόρμες', items: ['Evera.world', 'Persei.io', 'Eternals Library', 'GitHub'] },
      { h: 'Επαφή', items: ['Telegram', 'Maximian Solomonidis', 'Krasnaya Polyana, Sochi'] },
    ],
    legal: '© Pontos AI · 2026',
    city: 'Trebizond · Krasnaya Polyana',
  },
};

PONTOS_CONTENT.tr = {
  nav: { work: 'Yol haritası', services: 'Kaynaklar', about: 'Ekip', contact: 'Destek', chat: 'Pontos AI' },
  hero: {
    coords: 'Karadeniz · MÖ 7. yy — günümüz',
    label: 'Bir dil koruma projesi',
    title1: 'Πόντος AI',
    title2: 'Language',
    title3Em: 'Engine',
    title3: '.',
    tagline: 'Pontus Rumcasının dijital beyni. 36.000+ kelime · 2.600 yıllık tarih · 20 lehçe bölgesi.',
    taglineLabel: '« Ζήτω ο Πόντος » — Yaşasın Pontus',
    cta: "Pontos AI ile konuş",
    ctaSecondary: 'Yol haritası',
    scroll: 'Kaydır · κύλιση',
  },
  marquee: ['Trabzon', 'Sinop', 'Samsun', 'Giresun', 'İstanbul', 'Kırım', 'Krasnaya Polyana'],
  stats: [
    { num: '36.000+', label: "Veritabanındaki kelime" },
    { num: '2.600', label: 'Yıllık tarih' },
    { num: '20', label: 'Lehçe bölgesi' },
    { num: '4', label: 'Alfabe · alf.' },
  ],
  manifesto: {
    label: 'Proje mimarisi · 01',
    title: 'Pontus Rumcası — ',
    titleEm: 'dijitalleşen yaşayan bir dil.',
    meta: [
      ['Kurucu', 'Maximian Solomonidis'],
      ['Merkezler', 'Krasnaya Polyana · Trabzon'],
      ['Platform', 'Persei.io · Evera.world'],
      ['Diller', 'RU · EN · ΕΛ · TR'],
    ],
    paragraphs: [
      <>Pontus Rumcası 2.600 yıllık bir mirası taşır — Karadeniz antik çağından Trabzon, Sinop ve diasporanın köylerine. Dilin <em>dijital beynini</em> inşa ediyoruz: sözlük, dilbilgisi, etimoloji ve anadil seslerini tek bir yaşayan sistemde.</>,
      <>Proje, akademik sözlükleri, folklor arşivlerini ve <em>yalnızca</em> doğrulanmış veriden cevap veren bir AI'ı bir araya getirir — uydurma yok. Kelime yoksa, sistem dürüstçe söyler.</>,
    ],
  },
  pillars: {
    label: 'Yetenekler · 02',
    title: 'Dört sütun,',
    titleEm: 'tek dil.',
    items: [
      { greek: '📖', name: 'Sözlük', desc: '36.000+ kelimede arama. Kart: Yunan, Kiril, Latin, etimoloji, lehçe, kaynak.' },
      { greek: '🔡', name: 'Her alfabe', desc: 'Sistem aynı kelimenin Yunan, Kiril, Latin ve Türk yazımını anlar.' },
      { greek: '🎯', name: 'Uydurma yok', desc: 'AI sadece veritabanından yanıt verir. Kelime yoksa dürüstçe söyler. Halüsinasyon yok.' },
      { greek: '🚧', name: 'Yakında', desc: 'Tarih, dilbilgisi, kültür ve şarkılarla tam sohbet — doğrudan bu siteye gömülü.' },
    ],
  },
  services: {
    label: 'Bilgi tabanı · 03',
    title: 'Edebiyat ',
    titleEm: 've kaynaklar.',
    items: [
      { num: '/01', title: <>Akademik <em>sözlükler</em></>, desc: 'Papanikolaou, Andriotis, Opatos — Pontus lehçesi üzerine klasik sözlük çalışmaları.' },
      { num: '/02', title: <>Folklor <em>arşivleri</em></>, desc: 'Şarkılar, atasözleri, masallar, ritüel metinler — dilin günlük yaşamdaki sesi.' },
      { num: '/03', title: <>Anadil <em>sesleri</em></>, desc: 'Pontus, Kafkasya, Yunanistan ve diaspora köylerinden saha kayıtları.' },
      { num: '/04', title: <>Beklenen <em>baskılar</em></>, desc: 'Yeni yayınlar, tezler ve eklenmek üzere hazırlanan arşiv materyali.' },
    ],
  },
  work: {
    label: 'Yol haritası · 04',
    title: 'Arşivden diyaloga ',
    titleEm: '20 aşama.',
    items: window.ROADMAP_DATA.tr,
  },
  chat: {
    label: 'Pontos AI · Dictionary Mode',
    title: "Pontus ile ",
    titleEm: 'konuş.',
    desc: '36.000+ kelime · Yunan · Kiril · Latin · Türk',
    placeholder: 'Herhangi bir alfabede bir kelime girin — Rusça, Yunanca, Latince veya Türkçe',
    examples: ['νερόν', 'su', 'aman', 'Τραπεζοῦς', 'kan', 'αίμαν'],
    cta: "Pontos AI'ı aç",
  },
  team: {
    label: 'Ekip · 05',
    title: 'Anadil konuşurları, akademisyenler, ',
    titleEm: 'mühendisler.',
    desc: 'Anadil konuşuru, filolog veya araştırmacı mısınız? Bize katılın — her ses paha biçilmez.',
    items: [
      { name: 'Maximian Solomonidis', role: 'AI Mühendisi, Persei.io & Evera.world Kurucusu, "Ebediler Kütüphanesi" Yaratıcısı.', link: 'https://persei.io/?start=ref_solo013-eternals' },
      { name: 'Mikhail Katanov', role: 'Anadil konuşuru, araştırmacı.' },
      { name: 'Konstantin Kesov', role: 'KRGOO "Yunan Ulusal-Kültürel Otonomisi Romiosini" Başkanı', link: 'https://romiosini.ru/' },
      { name: 'Ivan Ananiadi', role: '"Patrida" Yunan Cemiyeti Başkanı, Krasnaya Polyana, Soçi', link: 'https://rusgreek.ru/krasnaya-polyanaundefinedsochinskaya-gorodskaya-obschestvennaya-organizatsiya' },
    ],
    cta: 'Projeye katıl',
  },
  support: {
    label: 'Destek · 06',
    title: 'Projeye ',
    titleEm: 'yardım edin.',
    desc: 'Destek bölümü geliştiriliyor. Şu an en iyi yardım — projeyi paylaşmak veya doğrudan iletişime geçmek.',
    items: [
      { icon: '🗣️', title: 'Anadil konuşuru', desc: 'Kelimeleri, deyimleri, şarkıları, atasözlerini kaydedin — sesiniz paha biçilmezdir.', cta: 'Yaz' },
      { icon: '🔬', title: 'Araştırmacı', desc: 'Veri doğrulama, etimoloji, dilbilgisi konularında yardım edin.', cta: 'Yaz' },
      { icon: '💛', title: 'Maddi', desc: 'Ödeme modülü yakında. Proje, dile duyulan sevgi ve coşkuyla yürüyor.', cta: 'Geliştirme aşamasında', disabled: true },
    ],
  },
  footer: {
    headline: <>Ζήτω ο <em>Πόντος.</em></>,
    sub: 'Yaşasın Pontus.',
    cta: 'İletişim',
    cols: [
      { h: 'Proje', items: ['Yol haritası', 'Kaynaklar', 'Ekip', 'Destek'] },
      { h: 'Platformlar', items: ['Evera.world', 'Persei.io', 'Eternals Library', 'GitHub'] },
      { h: 'İletişim', items: ['Telegram', 'Maximian Solomonidis', 'Krasnaya Polyana, Soçi'] },
    ],
    legal: '© Pontos AI · 2026',
    city: 'Trabzon · Krasnaya Polyana',
  },
};

window.PONTOS_CONTENT = PONTOS_CONTENT;
